/**
 * Programmatic SEO page definitions for TimrX.
 * Each entry generates a unique, Google-indexable landing page.
 */

export const SEO_PAGES = {
  // ─── /3d-models/:slug pages ───
  '3d-models': {
    base: '/3d-models',
    pages: [
      { slug: 'dragon', title: 'AI Dragon 3D Model Generator', h1: 'Create Dragon 3D Models with AI', desc: 'Generate stunning dragon 3D models from text prompts. Crystal dragons, fire drakes, wyverns — AI-powered text-to-3D creation ready for 3D printing and game engines.', prompt: 'Crystal dragon with iridescent scales perched on volcanic rock, fantasy art style', category: 'Fantasy', keywords: 'dragon 3D model, AI dragon generator, fantasy 3D model, dragon STL, dragon GLB',
        tips: [
          'Specify scale type (smooth, ridged, crystalline) to dramatically change the dragon\'s look',
          'Include a pose description like "coiled", "in flight", or "rearing up" for dynamic results',
          'Mention wing membrane details — translucent, leathery, or feathered wings each give a distinct style',
          'Add an environment element (lava, ice cave, mountain peak) to ground the model in context'
        ],
        useCases: [
          { title: 'Tabletop Gaming', desc: 'Generate unique dragon miniatures for D&D encounters, boss fights, and campaign centerpieces without sculpting from scratch.' },
          { title: 'Game Development', desc: 'Rapidly prototype dragon enemies, mounts, and NPCs for RPGs and adventure games with export to Unity or Unreal.' },
          { title: 'Collectible Figurines', desc: 'Design one-of-a-kind dragon figurines for resin printing, painting, and display or sale.' }
        ],
        relatedPrompts: [
          'Fire-breathing dragon mid-flight over a medieval village, cinematic lighting',
          'Baby dragon hatching from a glowing egg, cute stylized proportions',
          'Skeletal undead dragon with tattered wings, necromancy dark fantasy style',
          'Eastern serpentine dragon coiled around a pagoda tower, jade texture',
          'Ice dragon with crystalline frost scales, breath of frozen mist'
        ],
        faq: [
          { q: 'Can I 3D print a dragon model generated by TimrX?', a: 'Yes. Export the GLB file, import it into your slicer (Cura, PrusaSlicer, etc.), and use the built-in Remesh and Print Check tools to ensure the mesh is watertight before printing on FDM or resin printers.' },
          { q: 'How detailed are the dragon scales and wings?', a: 'The AI generates high-fidelity surface detail including individual scales, wing membranes, and horn textures. You can increase detail by adding descriptors like "intricate" or "hyper-detailed" in your prompt.' },
          { q: 'What file formats can I export dragon models in?', a: 'TimrX supports GLB and GLTF export. These formats are compatible with Blender, Unity, Unreal Engine, and all major 3D printing slicers.' }
        ]
      },
      { slug: 'robot', title: 'AI Robot 3D Model Generator', h1: 'Create Robot 3D Models with AI', desc: 'Generate detailed robot and mech 3D models from text descriptions. Humanoid robots, mechs, androids — export GLB/GLTF for printing or game development.', prompt: 'Futuristic humanoid robot with chrome armor plates and glowing blue joints', category: 'Sci-Fi', keywords: 'robot 3D model, AI robot generator, mech 3D model, robot STL',
        tips: [
          'Specify the robot archetype — humanoid, quadruped, spider-bot, or drone — to set the silhouette',
          'Mention material finishes like brushed steel, matte polymer, or battle-scarred paint for realism',
          'Include functional details such as sensor arrays, hydraulic pistons, or antenna dishes',
          'Describe the era or universe style (retro sci-fi, cyberpunk, military) for cohesive design'
        ],
        useCases: [
          { title: 'Concept Art Prototyping', desc: 'Quickly visualise robot concepts in 3D before committing to full production modelling for films or games.' },
          { title: 'Educational Models', desc: 'Create robot models for STEM presentations, robotics courses, and classroom demonstrations.' },
          { title: 'Toy and Kit Design', desc: 'Prototype action figure and model kit designs with articulated joints ready for 3D printing.' }
        ],
        relatedPrompts: [
          'Steampunk automaton with brass gears and a top hat, Victorian era style',
          'Giant construction mech with crane arm and caterpillar tracks, industrial design',
          'Tiny companion drone with propellers and a camera eye, cute sci-fi style',
          'War-damaged android with exposed wiring and cracked faceplate, dystopian',
          'Sleek household assistant robot with soft rounded panels, minimalist design'
        ],
        faq: [
          { q: 'Can I create articulated robot models for animation?', a: 'The AI generates a single-pose mesh. For animation, import the GLB into Blender and add an armature. The clean topology from TimrX\'s Remesh tool makes rigging straightforward.' },
          { q: 'How do I get a specific robot style like mecha or cyberpunk?', a: 'Include the style keyword directly in your prompt — for example "cyberpunk patrol robot" or "anime mecha suit". The AI uses these cues to shape proportions, surface detail, and overall aesthetic.' },
          { q: 'Are robot models suitable for resin printing?', a: 'Yes. Use the Print Check tool to verify wall thickness and overhangs. Resin printing captures fine details like panel lines, bolts, and sensor arrays especially well.' }
        ]
      },
      { slug: 'character', title: 'AI Character 3D Model Generator', h1: 'Create Character 3D Models with AI', desc: 'Generate unique character 3D models — heroes, villains, NPCs, and figurines. AI-powered text-to-3D for game developers, tabletop gamers, and artists.', prompt: 'Fantasy warrior in ornate armor, holding a shield, heroic pose, tabletop miniature style', category: 'Characters', keywords: 'character 3D model, AI character creator, figurine generator, NPC 3D model',
        tips: [
          'Define the character\'s class or role (warrior, mage, rogue) to guide proportions and gear',
          'Specify a pose — action poses like "mid-swing" create more dynamic miniatures than static T-poses',
          'Add clothing and accessory details like cloaks, belts, and pouches for richer results',
          'Mention an art style (realistic, anime, chibi, low-poly) to control the overall aesthetic'
        ],
        useCases: [
          { title: 'Tabletop RPG Miniatures', desc: 'Generate custom player characters, villains, and NPCs for Dungeons & Dragons, Pathfinder, and other tabletop RPGs.' },
          { title: 'Indie Game Assets', desc: 'Create unique character models for indie games without hiring a 3D artist — export directly to your game engine.' },
          { title: 'Custom Figurines', desc: 'Design personalised figurines as gifts, cake toppers, or collectibles and print them on a resin printer.' },
          { title: 'Storyboarding', desc: 'Rapidly generate character models for 3D storyboards, animatics, and pre-visualisation in film production.' }
        ],
        relatedPrompts: [
          'Elven ranger with a longbow, forest green cloak, crouching pose, fantasy miniature',
          'Cyberpunk street samurai with neon tattoos and a katana, urban gritty style',
          'Pirate captain with a tricorn hat, peg leg, and parrot on shoulder, stylised cartoon',
          'Medieval blacksmith with leather apron, hammer, and tongs at an anvil, realistic',
          'Sci-fi space marine in power armor with a plasma rifle, heroic stance'
        ],
        faq: [
          { q: 'Can I generate characters in a specific art style?', a: 'Yes. Include the style in your prompt — "anime style", "Pixar-like", "grimdark realistic", etc. The AI adapts proportions, shading cues, and detail levels to match.' },
          { q: 'How do I create matching sets of characters?', a: 'Use a consistent style phrase across prompts (e.g., "tabletop miniature, 32mm scale, high detail") and keep the environment or faction keywords the same to maintain visual cohesion.' },
          { q: 'Are character models textured?', a: 'Models are generated with vertex colours and surface detail baked in. For full PBR textures, import the GLB into Blender and use texture painting or baking workflows.' }
        ]
      },
      { slug: 'vehicle', title: 'AI Vehicle 3D Model Generator', h1: 'Create Vehicle 3D Models with AI', desc: 'Generate cars, spaceships, tanks, and more as 3D models. AI text-to-3D vehicle creation with GLB export for games, animation, and 3D printing.', prompt: 'Retro 1960s racing car with chrome details, vintage red paint, low-poly style', category: 'Vehicles', keywords: 'vehicle 3D model, AI car generator, spaceship 3D model, vehicle GLB',
        tips: [
          'Name a specific vehicle class (sedan, pickup, sports car, tank) to anchor the shape',
          'Add era and style cues like "1950s retro", "near-future concept", or "WW2 military" for accuracy',
          'Describe paint finish and materials — matte, chrome, carbon fiber, rust patina — for surface variety',
          'Include camera angle hints like "three-quarter view" to influence the generated perspective'
        ],
        useCases: [
          { title: 'Game Asset Libraries', desc: 'Build vehicle fleets for racing games, open-world titles, or city simulators without manual modelling.' },
          { title: 'Product Visualisation', desc: 'Prototype vehicle concepts and colour variations for client presentations and pitch decks.' },
          { title: 'Diorama and Scale Models', desc: 'Generate vehicles at any scale for diorama scenes, railway models, or architectural visualisations.' }
        ],
        relatedPrompts: [
          'Military Humvee with desert camo, mounted turret, dusty battlefield setting',
          'Futuristic hover taxi, transparent canopy, neon city reflections, cyberpunk',
          'Vintage Volkswagen camper van, pastel blue and white, surf beach setting',
          'Armoured personnel carrier with reactive armour plates, olive drab, modern military',
          'Formula 1 car with sponsor livery, open cockpit, pit lane backdrop'
        ],
        faq: [
          { q: 'Can I generate vehicles with interiors?', a: 'The AI focuses on exterior geometry and surface detail. For interior cabins, generate the exterior first, then model the interior separately in Blender using the exported GLB as reference.' },
          { q: 'How accurate are the proportions for real vehicle types?', a: 'The AI understands common vehicle silhouettes well. Including the make, model, or class (e.g., "SUV", "sports coupe") produces recognisable proportions, though results are original designs, not exact replicas.' },
          { q: 'Can I use generated vehicles in a commercial game?', a: 'Yes. Models generated on TimrX are yours to use in personal and commercial projects, including games, animations, and product renders.' }
        ]
      },
      { slug: 'animal', title: 'AI Animal 3D Model Generator', h1: 'Create Animal 3D Models with AI', desc: 'Generate realistic and stylized animal 3D models. Dogs, cats, dinosaurs, mythical creatures — AI-powered creation ready for printing and rendering.', prompt: 'Majestic wolf howling at the moon, detailed fur texture, forest clearing', category: 'Nature', keywords: 'animal 3D model, AI animal generator, pet 3D model, dinosaur STL',
        tips: [
          'Specify the animal species precisely — "golden retriever" gives much better results than just "dog"',
          'Describe the pose and behaviour (running, sitting, pouncing) for a more lifelike result',
          'Add fur, feather, or scale texture descriptors to improve surface detail',
          'Choose between realistic and stylised (low-poly, cartoon, chibi) to match your project needs'
        ],
        useCases: [
          { title: 'Wildlife Education', desc: 'Create 3D animal models for biology lessons, museum displays, and interactive educational apps.' },
          { title: 'Pet Portraits', desc: 'Generate a 3D model of a pet breed for personalised gifts, memorial figurines, or desk ornaments.' },
          { title: 'Game Fauna', desc: 'Populate game worlds with diverse wildlife — forest creatures, ocean life, or fantasy beasts — exported directly to your engine.' },
          { title: 'Animation Pre-vis', desc: 'Quickly generate animal stand-ins for animation blocking and storyboard pre-visualisation.' }
        ],
        relatedPrompts: [
          'Tyrannosaurus rex mid-roar, hyper-detailed scales, museum exhibit style',
          'Persian cat lounging on a velvet cushion, fluffy fur, warm studio lighting',
          'Eagle in flight with spread wings, photorealistic feathers, mountain backdrop',
          'Koi fish swimming through lily pads, Japanese woodblock art style',
          'Dire wolf with battle scars, thick winter coat, snowy tundra setting'
        ],
        faq: [
          { q: 'Can the AI generate realistic fur and feather textures?', a: 'The AI captures the visual appearance of fur and feathers in the surface geometry and vertex colours. For strand-level fur, you would add a hair particle system in Blender after export.' },
          { q: 'Can I generate extinct animals like dinosaurs?', a: 'Absolutely. The AI handles dinosaurs, prehistoric mammals, and other extinct species well. Include scientific or pop-culture references in your prompt for the look you want.' },
          { q: 'How do I make a specific dog or cat breed?', a: 'Name the breed directly in your prompt — e.g., "Shiba Inu sitting, detailed fur, studio lighting". The more specific you are about breed traits, the more accurate the result.' }
        ]
      },
      { slug: 'architecture', title: 'AI Architecture 3D Model Generator', h1: 'Create Architecture 3D Models with AI', desc: 'Generate buildings, temples, towers, and architectural structures as 3D models. AI text-to-3D for architects, game designers, and hobbyists.', prompt: 'Greek temple ruins with marble columns, overgrown vines, photorealistic weathering', category: 'Architecture', keywords: 'architecture 3D model, building generator, temple 3D model, house STL',
        tips: [
          'Name an architectural style (Gothic, Art Deco, Brutalist, Japanese) to guide the overall form',
          'Mention weathering, age, and condition — "pristine", "ancient ruins", "overgrown" — for atmosphere',
          'Include scale reference like "single-storey cottage" vs "towering cathedral" for correct proportions',
          'Add environment context (hilltop, city block, underwater) to influence surrounding geometry'
        ],
        useCases: [
          { title: 'Game Environment Design', desc: 'Rapidly generate buildings, ruins, and landmarks for open-world games, RPG maps, and level design blockouts.' },
          { title: 'Architectural Concept Exploration', desc: 'Explore building forms, facade ideas, and spatial layouts in 3D before committing to CAD drawings.' },
          { title: 'Tabletop Terrain', desc: 'Create printable terrain pieces — taverns, towers, bridges — for D&D and wargaming tabletops.' }
        ],
        relatedPrompts: [
          'Cyberpunk skyscraper with holographic billboards and rooftop gardens, neon-lit night',
          'Medieval stone watchtower on a cliff edge, mossy walls, flag on top',
          'Japanese torii gate at a mountain shrine, cherry blossom trees, serene morning',
          'Art Deco cinema facade with neon marquee sign, 1930s urban street',
          'Ruined colosseum half-buried in sand, desert wasteland, post-apocalyptic'
        ],
        faq: [
          { q: 'Are AI-generated buildings architecturally accurate?', a: 'The AI captures the visual essence and proportions of named styles (Gothic, Colonial, Modernist, etc.) but does not produce structurally engineered plans. It is ideal for concept art, game assets, and visual reference.' },
          { q: 'Can I generate interior layouts?', a: 'The AI primarily generates exterior forms and visible interior details like windows and doorways. For full interior rooms, generate them as separate models and assemble in Blender or your game engine.' },
          { q: 'What scale are architecture models generated at?', a: 'Models are generated at a relative scale. You can resize them in any 3D application. For 3D printing terrain, scale to your preferred tabletop standard (28mm, 32mm, etc.) in your slicer.' }
        ]
      },
      { slug: 'weapon', title: 'AI Weapon & Prop 3D Model Generator', h1: 'Create Weapon & Prop 3D Models with AI', desc: 'Generate swords, shields, staffs, sci-fi weapons, and game props as 3D models. AI-powered asset creation for game developers and cosplayers.', prompt: 'Enchanted sword with glowing blue runes embedded in a mossy stone altar, fantasy style', category: 'Fantasy', keywords: 'weapon 3D model, sword generator, prop 3D model, game asset GLB',
        tips: [
          'Name the weapon type precisely — longsword, war hammer, plasma rifle, staff — to set the base shape',
          'Describe enchantment effects like glowing runes, elemental auras, or ethereal particles for fantasy weapons',
          'Include grip and hilt details (leather wrapping, gem pommel, crossguard shape) for added realism',
          'Mention the intended display — "wall mount", "held in hand", "embedded in stone" — to guide the pose'
        ],
        useCases: [
          { title: 'Game Weapon Assets', desc: 'Generate swords, axes, staffs, and firearms for inventory systems, loot drops, and in-game shops.' },
          { title: 'Cosplay Props', desc: 'Design custom weapon props for cosplay, scale them up, and 3D print in sections for assembly and painting.' },
          { title: 'Tabletop Accessories', desc: 'Create weapon racks, treasure piles, and individual weapon props for tabletop diorama scenes.' },
          { title: 'Concept Portfolios', desc: 'Rapidly iterate on weapon concepts in 3D for game design portfolios and art director reviews.' }
        ],
        relatedPrompts: [
          'Viking battle axe with knotwork engravings, leather-wrapped handle, bloodstained edge',
          'Sci-fi energy sword with transparent plasma blade, sleek chrome hilt, holographic HUD',
          'Wizard\'s gnarled oak staff topped with a floating crystal orb, arcane runes',
          'Ornate tower shield with lion crest, polished steel, dented from battle',
          'Steampunk revolver with brass gears, copper pipes, and wooden grip'
        ],
        faq: [
          { q: 'Can I print weapons at full cosplay scale?', a: 'Yes. Export the GLB, import into your slicer, and scale to full size. For large props like swords and staffs, split the model into sections using Blender\'s boolean tools, print each part, and glue them together.' },
          { q: 'How do I get glowing or magical effects in the 3D model?', a: 'Describe the effect in your prompt ("glowing blue runes", "fiery blade"). The AI bakes the visual glow into vertex colours. For real-time glow in a game engine, add emissive materials to those regions after import.' },
          { q: 'Are weapon models game-ready with low poly counts?', a: 'Generated meshes are medium-density. For game-ready assets, use TimrX\'s Remesh tool to reduce poly count, then export. Most models work directly in modern engines without optimisation.' }
        ]
      },
      { slug: 'miniature', title: 'AI Miniature 3D Model Generator', h1: 'Create Tabletop Miniatures with AI', desc: 'Generate tabletop gaming miniatures, dioramas, and figurines. AI text-to-3D creation optimized for FDM and resin 3D printing.', prompt: 'Tabletop miniature wizard casting a spell, robes flowing, diorama base with runes', category: 'Characters', keywords: 'miniature 3D model, tabletop miniature generator, D&D miniature, wargaming STL',
        tips: [
          'Add "tabletop miniature" or "32mm scale" to your prompt so the AI optimises proportions for printing',
          'Describe a scenic base (cobblestone, dungeon floor, grass mound) to get a display-ready mini',
          'Keep the pose compact — outstretched arms and thin weapons print better when close to the body',
          'Specify the faction or army theme for cohesive unit sets (e.g., "undead legion", "elven guard")'
        ],
        useCases: [
          { title: 'D&D Campaign Minis', desc: 'Generate unique miniatures for every player character and NPC in your Dungeons & Dragons campaign without buying pre-made sets.' },
          { title: 'Wargaming Armies', desc: 'Rapidly create rank-and-file soldiers, heroes, and monsters for Warhammer, Kings of War, and other wargames.' },
          { title: 'Diorama Scenes', desc: 'Build narrative diorama scenes with custom figures, terrain, and props all generated from text.' }
        ],
        relatedPrompts: [
          'Dwarf berserker with twin axes, braided beard, rocky base, 32mm tabletop miniature',
          'Necromancer raising skeletons from the ground, dark robes, graveyard diorama base',
          'Mounted knight on armoured warhorse, lance couched, tournament field base',
          'Goblin shaman with a bone staff and shrunken head necklace, swamp base',
          'Space marine heavy weapons specialist, kneeling firing pose, rubble base'
        ],
        faq: [
          { q: 'What printer is best for AI-generated miniatures?', a: 'Resin printers (MSLA/DLP) deliver the best detail at miniature scale. FDM printers work for larger figures (54mm+). Use TimrX\'s Print Check tool to validate your model for either technology.' },
          { q: 'How do I add a base to my miniature?', a: 'Include "diorama base" or "scenic base" in your prompt and the AI will generate one. Alternatively, add a standard 25mm or 32mm round base in your slicer or Blender before printing.' },
          { q: 'Can I generate a matching set of miniatures?', a: 'Yes. Keep your style keywords consistent across prompts (e.g., "32mm tabletop miniature, high fantasy, detailed") and vary only the character description to produce a cohesive warband or party.' }
        ]
      },
      { slug: 'furniture', title: 'AI Furniture 3D Model Generator', h1: 'Create Furniture 3D Models with AI', desc: 'Generate chairs, tables, shelves, and interior objects as 3D models. AI-powered design for interior visualisation and product prototyping.', prompt: 'Mid-century modern lounge chair, walnut wood frame, leather cushion, studio lighting', category: 'Architecture', keywords: 'furniture 3D model, chair generator, interior design 3D, product prototype',
        tips: [
          'Name a design movement (mid-century modern, Scandinavian, industrial, Art Nouveau) for cohesive style',
          'Specify materials — walnut, oak, marble, brushed steel, leather — the AI renders them distinctly',
          'Include dimensions or scale hints like "compact desk" or "king-size bed frame" for proportions',
          'Describe the setting (living room, office, outdoor patio) to influence contextual details'
        ],
        useCases: [
          { title: 'Interior Design Mockups', desc: 'Generate furniture models for room visualisations, client mood boards, and interior staging without sourcing stock 3D assets.' },
          { title: 'Product Prototyping', desc: 'Explore chair, table, and shelf designs in 3D before building physical prototypes or commissioning CAD drawings.' },
          { title: 'Miniature Dollhouse Parts', desc: 'Create scaled-down furniture pieces for dollhouses, dioramas, and architectural scale models for 3D printing.' }
        ],
        relatedPrompts: [
          'Industrial pipe bookshelf with reclaimed wood planks, loft apartment setting',
          'Japanese low dining table with floor cushions, tatami mat room, warm ambient light',
          'Ergonomic standing desk with monitor arm and cable management, modern office',
          'Ornate Victorian chaise longue with tufted velvet upholstery, mahogany legs',
          'Outdoor wicker hanging egg chair with cushions, boho garden patio'
        ],
        faq: [
          { q: 'Can I use furniture models for client presentations?', a: 'Yes. Export as GLB, import into your rendering tool (Blender, SketchUp, etc.), and place the furniture in your scene. The models work well for mood boards, room mockups, and concept presentations.' },
          { q: 'How realistic are the wood and fabric textures?', a: 'The AI generates convincing surface detail for wood grain, leather, fabric weave, and metal finishes. For photorealistic renders, you can enhance materials with PBR texture maps in Blender after import.' },
          { q: 'Can I 3D print furniture models as miniatures?', a: 'Absolutely. Scale the model down in your slicer to 1:12 or 1:24 scale for dollhouse furniture, or print at larger scales for desk display pieces.' }
        ]
      },
      { slug: 'spaceship', title: 'AI Spaceship 3D Model Generator', h1: 'Create Spaceship 3D Models with AI', desc: 'Generate spaceships, starfighters, and sci-fi vessels as 3D models. AI text-to-3D for game devs, filmmakers, and sci-fi enthusiasts.', prompt: 'Sleek interstellar cruiser with ion engines, modular hull panels, deep space backdrop', category: 'Sci-Fi', keywords: 'spaceship 3D model, AI spaceship generator, starship GLB, sci-fi vehicle STL',
        tips: [
          'Define the ship class (fighter, freighter, capital ship, shuttle) to set the scale and silhouette',
          'Describe propulsion details — ion engines, rocket nozzles, solar sails — for a believable design',
          'Add hull details like panel lines, antenna arrays, docking ports, and turrets for complexity',
          'Mention a sci-fi sub-genre (hard sci-fi, space opera, retrofuturism) to guide the aesthetic'
        ],
        useCases: [
          { title: 'Space Game Assets', desc: 'Generate fleets of unique starships for space simulators, strategy games, and sci-fi RPGs.' },
          { title: 'Film Pre-visualisation', desc: 'Rapidly create spaceship models for sci-fi film storyboards, VFX pre-vis, and pitch materials.' },
          { title: 'Display Models', desc: 'Design and 3D print custom spaceship models for desk display, shelf collections, or fan art.' },
          { title: 'Worldbuilding', desc: 'Visualise ships from your sci-fi novel, RPG setting, or homebrew universe to share with collaborators.' }
        ],
        relatedPrompts: [
          'Bulky mining vessel with ore processing arms, asteroid belt backdrop, industrial sci-fi',
          'Sleek diplomatic yacht with mirrored hull, elegant swept wings, orbital station dock',
          'Battered smuggler freighter with mismatched hull plates, hidden compartments, docking bay',
          'Alien organic ship with chitinous hull, bioluminescent veins, deep space nebula',
          'Retro rocket ship with fins and porthole windows, 1950s pulp sci-fi art style'
        ],
        faq: [
          { q: 'Can I generate spaceships with specific design inspirations?', a: 'Yes. Reference a style in your prompt — "Star Wars-inspired freighter", "hard sci-fi realistic", or "Moebius comic style" — and the AI will adapt the design language accordingly.' },
          { q: 'How complex are the generated spaceship models?', a: 'Models include hull panelling, engine detail, and surface greebles. For interior layouts or cross-sections, generate those as separate models and combine them in your 3D application.' },
          { q: 'Can I print large capital ships?', a: 'Yes. Scale in your slicer and split into sections for printing if the model exceeds your build volume. The Remesh tool ensures watertight geometry for clean prints at any scale.' }
        ]
      },
    ]
  },

  // ─── /converters/:slug pages ───
  'converters': {
    base: '/converters',
    pages: [
      { slug: 'avi-to-mp4', title: 'Free AVI to MP4 Converter Online', h1: 'Free AVI to MP4 Converter', desc: 'Convert AVI video files to MP4 online with TimrX. Temporary server-side processing, no permanent S3 storage, and a clean MP4 download.', prompt: 'Upload an AVI file, convert it to MP4, then download the converted video.', category: 'Free Converter', keywords: 'free AVI to MP4 converter, AVI converter online, convert AVI to MP4, video converter',
        kind: 'converter', ctaUrl: '/avi-to-mp4', ctaLabel: 'Open AVI Converter', watermark: 'MP4',
        tips: [
          'Use AVI source files that are already finalized and playable before uploading',
          'For faster conversion, keep the file short and avoid very large uncompressed AVI exports',
          'The converter writes temporary files only while the request is running',
          'MP4 output is easier to share, preview, and upload than legacy AVI files'
        ],
        useCases: [
          { title: 'Browser Playback', desc: 'Convert older AVI exports into MP4 files that play more reliably in modern browsers and devices.' },
          { title: 'Social Uploads', desc: 'Prepare videos for platforms and apps that prefer H.264 MP4 instead of AVI containers.' },
          { title: 'Client Delivery', desc: 'Turn local AVI renders into a common MP4 format before sending previews to clients or collaborators.' }
        ],
        relatedPrompts: [
          'Free AVI to MP4 converter',
          'Convert AVI video to browser-friendly MP4',
          'Temporary video conversion with no permanent storage',
          'Online AVI converter for TimrX users',
          'Download converted MP4 after upload'
        ],
        faq: [
          { q: 'Is the TimrX AVI to MP4 converter free?', a: 'Yes. The AVI to MP4 converter is available as a free TimrX utility.' },
          { q: 'Are AVI files stored permanently?', a: 'No. The converter uses temporary server-side storage while the conversion runs and removes the files after the response finishes.' },
          { q: 'What format does the converter download?', a: 'It downloads an MP4 file encoded for broad playback compatibility.' }
        ]
      },
      { slug: 'glb-to-stl', title: 'Free GLB to STL Converter Online', h1: 'Free GLB to STL Converter', desc: 'Convert GLB 3D models to STL in your browser with TimrX. Prepare AI-generated GLB files for slicing, repair, and 3D printing.', prompt: 'Upload a GLB model and export an STL file for 3D printing workflows.', category: '3D Converter', keywords: 'GLB to STL converter, free GLB converter, convert GLB to STL, 3D print STL converter',
        kind: 'converter', ctaUrl: '/converter', ctaLabel: 'Open 3D Converter', watermark: 'STL',
        tips: [
          'Use STL when your slicer or repair tool requires geometry-only files',
          'Keep GLB for color and material workflows because STL does not preserve colors',
          'Run print checks after conversion if the model is intended for physical printing',
          'Set a target print height before export when scale matters'
        ],
        useCases: [
          { title: '3D Printing', desc: 'Convert AI-generated GLB models into STL files for slicers and mesh repair tools.' },
          { title: 'Geometry Repair', desc: 'Use STL export as part of a cleanup workflow when color data is not required.' },
          { title: 'Slicer Compatibility', desc: 'Prepare files for older slicers that do not handle GLB imports reliably.' }
        ],
        relatedPrompts: ['GLB to STL converter', 'convert AI GLB to STL', 'free 3D print file converter', 'browser STL export', 'GLB model to slicer format'],
        faq: [
          { q: 'Does STL keep GLB colors?', a: 'No. STL is a geometry-only format and does not preserve GLB colors or textures.' },
          { q: 'Is GLB to STL conversion client-side?', a: 'Yes. The TimrX 3D converter processes model conversion in the browser.' },
          { q: 'Can I use the STL in Bambu Studio?', a: 'Yes, but use 3MF or GLB workflows when you need color information.' }
        ]
      },
      { slug: 'glb-to-obj', title: 'Free GLB to OBJ Converter Online', h1: 'Free GLB to OBJ Converter', desc: 'Convert GLB files to OBJ online with TimrX. Export 3D models for Blender, modeling tools, and game asset cleanup workflows.', prompt: 'Upload a GLB model and export OBJ for editing in common 3D tools.', category: '3D Converter', keywords: 'GLB to OBJ converter, convert GLB to OBJ, free OBJ converter, online 3D converter',
        kind: 'converter', ctaUrl: '/converter', ctaLabel: 'Open 3D Converter', watermark: 'OBJ',
        tips: [
          'Use OBJ for broad compatibility with modeling and inspection tools',
          'Check material support in the target app before relying on color data',
          'Use GLB for compact sharing and OBJ for older 3D pipelines',
          'Review scale and orientation after export'
        ],
        useCases: [
          { title: 'Blender Editing', desc: 'Move GLB models into OBJ-based editing and cleanup workflows.' },
          { title: 'Legacy Pipelines', desc: 'Export assets for tools that prefer OBJ over modern GLB containers.' },
          { title: 'Model Inspection', desc: 'Use OBJ when you need simple mesh interchange across many 3D applications.' }
        ],
        relatedPrompts: ['GLB to OBJ converter', 'convert GLB model to OBJ', 'free OBJ export tool', 'browser 3D converter', 'GLB file conversion'],
        faq: [
          { q: 'When should I use OBJ instead of GLB?', a: 'Use OBJ for broad tool compatibility and GLB for compact files that preserve more scene data.' },
          { q: 'Does the converter require an account?', a: 'The 3D file converter is a free browser tool and does not require sign-up for basic conversion.' },
          { q: 'Are files uploaded for GLB to OBJ conversion?', a: 'No. The 3D converter runs in the browser so files stay on the device.' }
        ]
      },
      { slug: 'obj-to-stl', title: 'Free OBJ to STL Converter Online', h1: 'Free OBJ to STL Converter', desc: 'Convert OBJ 3D files to STL directly in your browser. Use TimrX to prepare mesh geometry for 3D printing and repair tools.', prompt: 'Upload an OBJ file and export STL for printing or mesh repair.', category: '3D Converter', keywords: 'OBJ to STL converter, convert OBJ to STL, free STL converter, 3D printing converter',
        kind: 'converter', ctaUrl: '/converter', ctaLabel: 'Open 3D Converter', watermark: 'STL',
        tips: [
          'Use OBJ to STL when you only need printable geometry',
          'Remember that STL does not carry materials, textures, or vertex colors',
          'Inspect the exported model for scale and orientation before slicing',
          'Repair non-watertight meshes before printing'
        ],
        useCases: [
          { title: 'Slicer Export', desc: 'Convert OBJ files to STL for slicers that expect classic 3D printing formats.' },
          { title: 'Mesh Cleanup', desc: 'Prepare simple geometry exports for repair, remeshing, or print validation.' },
          { title: 'Workshop Sharing', desc: 'Create STL files that are easy to share with print shops and maker spaces.' }
        ],
        relatedPrompts: ['OBJ to STL converter', 'free STL export', 'OBJ file to 3D print format', 'browser OBJ converter', 'online mesh converter'],
        faq: [
          { q: 'Will OBJ materials appear in STL?', a: 'No. STL removes material and texture information.' },
          { q: 'Can I convert OBJ to STL in the browser?', a: 'Yes. TimrX converts supported 3D files client-side in the browser.' },
          { q: 'Is STL always best for printing?', a: 'STL is widely supported, but 3MF is better when color, units, or richer print data matters.' }
        ]
      },
      { slug: 'fbx-to-glb', title: 'Free FBX to GLB Converter Online', h1: 'Free FBX to GLB Converter', desc: 'Convert FBX files to GLB online with TimrX. Prepare 3D assets for web previews, sharing, game engines, and browser workflows.', prompt: 'Upload an FBX file and export a compact GLB for web-friendly 3D workflows.', category: '3D Converter', keywords: 'FBX to GLB converter, convert FBX to GLB, free GLB converter, web 3D converter',
        kind: 'converter', ctaUrl: '/converter', ctaLabel: 'Open 3D Converter', watermark: 'GLB',
        tips: [
          'Use GLB when you want a compact single-file web 3D asset',
          'Check animations and materials after conversion in the target viewer',
          'Prefer GLB for browser previews and product showcases',
          'Keep a source FBX copy for authoring and rigging edits'
        ],
        useCases: [
          { title: 'Web 3D Delivery', desc: 'Turn FBX assets into GLB files that are easier to preview and share online.' },
          { title: 'Game Asset Transfer', desc: 'Convert between common engine interchange formats during asset cleanup.' },
          { title: 'Portfolio Models', desc: 'Create GLB files for interactive previews on websites and galleries.' }
        ],
        relatedPrompts: ['FBX to GLB converter', 'convert FBX for web', 'free GLB export', 'browser 3D file converter', 'FBX web preview'],
        faq: [
          { q: 'Why convert FBX to GLB?', a: 'GLB is compact, web-friendly, and commonly used for browser-based 3D previews.' },
          { q: 'Does conversion preserve animation?', a: 'Supported animation data can be carried through where the browser importer and exporter support it.' },
          { q: 'Are FBX files uploaded?', a: 'The 3D converter is designed for client-side browser conversion.' }
        ]
      },
      { slug: 'gltf-to-glb', title: 'Free GLTF to GLB Converter Online', h1: 'Free GLTF to GLB Converter', desc: 'Convert GLTF assets to a single GLB file with TimrX. Package web 3D models into one compact file for sharing and deployment.', prompt: 'Upload GLTF assets and export a single GLB file for web or app delivery.', category: '3D Converter', keywords: 'GLTF to GLB converter, convert GLTF to GLB, free GLB packer, web 3D converter',
        kind: 'converter', ctaUrl: '/converter', ctaLabel: 'Open 3D Converter', watermark: 'GLB',
        tips: [
          'Use GLB when you want one file instead of separate GLTF, bin, and texture files',
          'Check that referenced textures are present before conversion',
          'Use GLB for easier upload, preview, and deployment workflows',
          'Keep original GLTF assets when you still need editable source files'
        ],
        useCases: [
          { title: 'Web Deployment', desc: 'Bundle GLTF scenes into GLB files for simpler hosting and loading.' },
          { title: 'Asset Sharing', desc: 'Send a single GLB file instead of a folder of dependent assets.' },
          { title: 'Viewer Compatibility', desc: 'Prepare models for viewers and apps that prefer GLB uploads.' }
        ],
        relatedPrompts: ['GLTF to GLB converter', 'pack GLTF as GLB', 'free web 3D converter', 'single file GLB export', 'browser GLTF converter'],
        faq: [
          { q: 'What is the difference between GLTF and GLB?', a: 'GLTF can reference separate files, while GLB packages the scene into one binary file.' },
          { q: 'Is GLB better for sharing?', a: 'Usually yes, because one file is easier to upload, store, and preview.' },
          { q: 'Does TimrX convert GLTF in the browser?', a: 'Yes. The 3D converter is built as a browser-based conversion tool.' }
        ]
      }
    ]
  },

  // ─── /text-to-3d/:slug pages ───
  'text-to-3d': {
    base: '/text-to-3d',
    pages: [
      { slug: 'dragon', title: 'Text to 3D Dragon — AI Generator', h1: 'Turn Text Into a 3D Dragon', desc: 'Type a description and get a detailed dragon 3D model. AI text-to-3D generation with GLB export for printing, games, and rendering.', prompt: 'A fearsome dragon with polished obsidian scales, glowing red eyes, dark fantasy style', category: 'Fantasy', keywords: 'text to 3D dragon, AI dragon, generate dragon model',
        tips: [
          'Describe the dragon\'s personality (fearsome, noble, ancient) and the AI reflects it in posture and expression',
          'Specify colour palette ("obsidian and crimson", "emerald and gold") for targeted colour results',
          'Include the dragon\'s size context — "towering over a village" vs "curled in a treasure hoard" — for scale cues',
          'Pair the dragon with a setting element like a lair, mountain, or battlefield for a richer scene'
        ],
        useCases: [
          { title: 'Book Cover Art', desc: 'Generate a 3D dragon and render it from dramatic angles for fantasy book covers, posters, and promotional art.' },
          { title: 'VTT Tokens', desc: 'Create top-down or isometric dragon renders for virtual tabletop platforms like Roll20 and Foundry VTT.' },
          { title: 'Fan Art and Merch', desc: 'Design original dragon models for fan art renders, T-shirt designs, and print-on-demand merchandise.' }
        ],
        relatedPrompts: [
          'Celestial dragon made of starlight and constellations, cosmic void background',
          'Swamp dragon with moss-covered scales, long neck, murky waters, dark atmosphere',
          'Mechanical clockwork dragon with brass wings and steam vents, steampunk style',
          'Two-headed dragon guarding a treasure hoard, cave interior, torch light'
        ],
        faq: [
          { q: 'How is text-to-3D different from image-to-3D for dragons?', a: 'Text-to-3D generates a model purely from your written description, giving the AI creative freedom. Image-to-3D uses a reference photo to match a specific look. Both produce exportable GLB files.' },
          { q: 'Can I specify the number of heads, wings, or limbs?', a: 'Yes. State it clearly in your prompt — "three-headed dragon" or "wingless serpentine dragon". The AI follows anatomical instructions, though very unusual configurations may need a few attempts.' }
        ]
      },
      { slug: 'robot', title: 'Text to 3D Robot — AI Generator', h1: 'Turn Text Into a 3D Robot', desc: 'Describe a robot and get a 3D model in minutes. AI-powered text-to-3D creation with full export support.', prompt: 'Bipedal patrol robot with sensor dome head, matte olive panels, utility belt', category: 'Sci-Fi', keywords: 'text to 3D robot, AI robot model, generate robot 3D',
        tips: [
          'Describe the robot\'s purpose (patrol, medical, construction, companion) and the design follows logically',
          'Mention joint types — ball joints, hydraulic pistons, flexible cables — for mechanical authenticity',
          'Specify size context: "palm-sized drone" vs "building-sized mech" changes the entire design',
          'Add wear and tear descriptors ("battle-damaged", "factory-new", "rusty") for character'
        ],
        useCases: [
          { title: 'Sci-Fi Illustration', desc: 'Generate robot models to render from any angle for science fiction illustrations, concept sheets, and pitch decks.' },
          { title: 'Stop-Motion Props', desc: 'Print small robot figurines for stop-motion animation projects and practical effects.' },
          { title: 'Board Game Pieces', desc: 'Create unique robot tokens and playing pieces for custom board games and sci-fi tabletop games.' }
        ],
        relatedPrompts: [
          'Underwater exploration robot with propellers, floodlights, and sonar dish, deep ocean',
          'Cute rounded companion bot with emoji face screen, pastel colours, kawaii style',
          'Heavy industrial loader mech with forklift arms, yellow caution stripes, warehouse',
          'Ancient stone golem with runic inscriptions, mossy joints, fantasy dungeon',
          'Nano-scale medical robot with needle arms and scanner eye, microscopic perspective'
        ],
        faq: [
          { q: 'Can I turn my text description into a poseable robot?', a: 'The AI generates a single-pose mesh. To make it poseable, import the GLB into Blender, separate limbs into objects, and add an armature with inverse kinematics for each joint.' },
          { q: 'What level of mechanical detail can I expect?', a: 'The AI generates visible panel lines, joints, sensors, and surface greebles. For internal mechanical details like gears and wiring, describe them as exposed or visible in your prompt.' }
        ]
      },
      { slug: 'house', title: 'Text to 3D House — AI Generator', h1: 'Turn Text Into a 3D House', desc: 'Describe any building and AI generates a 3D model. Houses, castles, cabins — export GLB for visualisation or printing.', prompt: 'Cozy forest cabin with stone chimney, snow on roof, warm light from windows', category: 'Architecture', keywords: 'text to 3D house, AI building model, generate house 3D',
        tips: [
          'Name the house style (Tudor, Cape Cod, A-frame, Mediterranean) for recognisable architecture',
          'Describe roofing material and wall finish — slate tiles, thatched roof, whitewashed walls — for texture variety',
          'Add surroundings like a garden, fence, driveway, or trees to create a complete scene',
          'Mention lighting conditions (warm evening glow, snowy morning, sunny day) to influence the mood'
        ],
        useCases: [
          { title: 'Real Estate Concept Art', desc: 'Generate house concepts for property development pitch decks, marketing materials, and early-stage design exploration.' },
          { title: 'Game World Buildings', desc: 'Populate villages, towns, and settlements in your game world with diverse and unique house models.' },
          { title: 'Model Railway Scenery', desc: 'Create HO or N-scale houses for model railway layouts and print them on a resin printer for fine detail.' }
        ],
        relatedPrompts: [
          'Treehouse village with rope bridges between giant oaks, fairy-tale style',
          'Modern glass box house on a hillside, infinity pool, sunset view',
          'Hobbit hole with round green door, garden on the roof, rolling hills',
          'Abandoned Victorian mansion with broken windows, overgrown garden, haunted atmosphere',
          'Futuristic Mars habitat dome with solar panels, red desert landscape'
        ],
        faq: [
          { q: 'Can I use the house model for architectural planning?', a: 'The models are best for visual reference and concept exploration. They are not dimensionally precise enough for construction drawings, but work well for mood boards, game assets, and early ideation.' },
          { q: 'How do I get a house with both exterior and interior?', a: 'Generate the exterior and interior as separate prompts. Combine them in Blender by placing the interior model inside the exterior shell. This gives you full control over room layout.' },
          { q: 'Can I generate a neighbourhood of different houses?', a: 'Yes. Generate each house individually with varied prompts, export all as GLB files, and arrange them in Blender or your game engine to build a street or neighbourhood scene.' }
        ]
      },
      { slug: 'sword', title: 'Text to 3D Sword — AI Generator', h1: 'Turn Text Into a 3D Sword', desc: 'Create custom sword and weapon 3D models from text. Fantasy blades, sci-fi weapons, historical arms — AI generation with GLB export.', prompt: 'Katana with black and gold tsuka wrapping, hamon line on blade, cherry blossom guard', category: 'Fantasy', keywords: 'text to 3D sword, AI weapon model, generate sword 3D',
        tips: [
          'Name the sword type (katana, broadsword, rapier, scimitar) for accurate blade shape and proportions',
          'Describe the blade finish — polished mirror, matte damascus, etched runes — for surface character',
          'Include scabbard or sheath details if you want the full weapon set, not just the bare blade',
          'Mention cultural origin (Japanese, Viking, Celtic, Arabian) to guide decorative motifs'
        ],
        useCases: [
          { title: 'RPG Loot Assets', desc: 'Generate unique sword models for loot tables, quest rewards, and legendary weapon sets in role-playing games.' },
          { title: 'Cosplay Replica Props', desc: 'Design a custom sword, scale it to full size, and 3D print it in sections for cosplay conventions and costume contests.' },
          { title: 'Historical Replica Study', desc: 'Recreate historical sword types — gladius, falchion, jian — for educational displays, museum mockups, and reference models.' },
          { title: 'Wall Art and Decor', desc: 'Print decorative sword models for wall mounts, shadow boxes, and themed room decor.' }
        ],
        relatedPrompts: [
          'Flaming greatsword with molten cracks along the blade, dark lord fantasy style',
          'Elegant elven longsword with leaf-shaped blade, silver vine hilt, moonlight glow',
          'Roman gladius with wooden grip, iron pommel, leather scabbard, historical style',
          'Cyber katana with neon edge, carbon fiber handle, holographic blade, cyberpunk',
          'Frozen ice sword with jagged crystalline blade, frost particles, arctic warrior'
        ],
        faq: [
          { q: 'How thin can sword blades be for 3D printing?', a: 'Very thin blades may need thickening for printing. Use the Print Check tool to identify areas below minimum wall thickness, then scale or adjust in your slicer. Resin printers handle thinner features better than FDM.' },
          { q: 'Can I generate a sword in its scabbard?', a: 'Yes. Include "with scabbard" or "sheathed" in your prompt. For a separate scabbard, generate it as a standalone model and pair it with the sword in your 3D application.' },
          { q: 'Will the AI capture details like hamon lines and engravings?', a: 'The AI renders surface details like hamon temper lines, rune engravings, and filigree patterns as geometry and vertex colour. Name these details explicitly in your prompt for the best results.' }
        ]
      },
      { slug: 'car', title: 'Text to 3D Car — AI Generator', h1: 'Turn Text Into a 3D Car', desc: 'Describe any vehicle and get a 3D model. Classic cars, supercars, concept vehicles — AI text-to-3D with full export.', prompt: 'Matte black supercar with aggressive body kit, carbon fiber accents, studio lighting', category: 'Vehicles', keywords: 'text to 3D car, AI car model, generate car 3D',
        tips: [
          'Specify the car segment (muscle car, hatchback, hypercar, off-roader) to nail the body shape',
          'Describe headlight and taillight design — round vintage, angular modern, LED strip — for front-end character',
          'Mention wheel style (wire spokes, deep-dish alloys, off-road knobbly tyres) for added detail',
          'Include a setting or backdrop (showroom floor, race track, desert highway) for context'
        ],
        useCases: [
          { title: 'Racing Game Fleets', desc: 'Generate diverse car models for racing games, from street racers to rally cars, each with unique body kits and liveries.' },
          { title: 'Automotive Design Exploration', desc: 'Quickly explore body shapes, proportions, and styling cues for car design projects and automotive portfolios.' },
          { title: 'Desk Display Models', desc: 'Create and 3D print custom car models for desk displays, gifts, and collector shelves.' }
        ],
        relatedPrompts: [
          'Classic 1967 muscle car with racing stripes, chrome bumpers, drag strip setting',
          'Electric concept car with smooth aerodynamic body, butterfly doors, auto show stage',
          'Rally car with mud splatters, roof-mounted lights, forest trail backdrop',
          'Lowrider with hydraulic suspension, candy paint, gold wire wheels, urban setting',
          'Post-apocalyptic car with welded armour plates, spikes, and a mounted turret'
        ],
        faq: [
          { q: 'Can I generate a specific real car make and model?', a: 'The AI generates original designs inspired by your description. It will capture the style and proportions of a described type (e.g., "sports coupe", "1960s muscle car") but produces unique, non-branded designs.' },
          { q: 'How do I get the best wheel and tyre detail?', a: 'Describe the wheel style in your prompt — "five-spoke alloy wheels with low-profile tyres" or "chrome wire wheels". The AI renders wheels as part of the overall model with matching detail level.' },
          { q: 'Can I render the car model with realistic lighting?', a: 'Export the GLB to Blender, set up an HDRI environment and studio lights, and render with Cycles or EEVEE for photorealistic results. The vertex colours from TimrX serve as a solid base material.' }
        ]
      },
      { slug: 'tree', title: 'Text to 3D Tree — AI Generator', h1: 'Turn Text Into a 3D Tree', desc: 'Generate tree and plant 3D models from text descriptions. Bonsai, oak, fantasy trees — AI creation for games, scenes, and printing.', prompt: 'Ancient bonsai tree growing from a cracked geode crystal, roots wrapping around gems', category: 'Nature', keywords: 'text to 3D tree, AI tree model, generate plant 3D',
        tips: [
          'Name the species (oak, cherry blossom, baobab, redwood) for recognisable trunk and canopy shapes',
          'Describe the season — "autumn with orange leaves", "bare winter branches", "full spring bloom" — for dramatic variation',
          'Add root and bark texture descriptors like "gnarled roots", "peeling birch bark", or "smooth trunk"',
          'Include a base element (forest floor, rocky cliff, cracked pavement) to anchor the tree in a scene'
        ],
        useCases: [
          { title: 'Game Environment Foliage', desc: 'Generate unique trees and plants to populate forests, parks, and alien landscapes in your game world.' },
          { title: 'Bonsai Art Prints', desc: 'Create intricate bonsai models, render from artistic angles, and produce prints for home decor or online art shops.' },
          { title: 'Tabletop Terrain Trees', desc: 'Print miniature trees for wargaming tabletops, D&D forest encounters, and diorama landscapes.' }
        ],
        relatedPrompts: [
          'Massive world-tree with a spiral staircase carved into the trunk, fantasy elven city in branches',
          'Dead twisted tree in a haunted graveyard, bats, full moon, horror atmosphere',
          'Cherry blossom tree in full bloom, petals falling, Japanese garden pond',
          'Alien bioluminescent mushroom tree on an exoplanet, glowing spores, sci-fi',
          'Mangrove tree with exposed roots in shallow water, tropical island setting'
        ],
        faq: [
          { q: 'Can the AI generate realistic leaf detail?', a: 'The AI represents foliage as clusters of leaf-like geometry with colour variation. For individual leaf-level detail, use Blender\'s particle system to add leaf planes to the generated trunk and branch structure.' },
          { q: 'How do I create a forest from a single tree model?', a: 'Generate several different tree models, export them as GLB files, and use your game engine\'s or Blender\'s scatter/instancing tools to populate an entire forest with natural variation.' },
          { q: 'Are tree models suitable for 3D printing?', a: 'Yes. Thicker tree styles (baobab, oak) print well on FDM. Delicate branches and leaves are better suited to resin printing. Use the Print Check tool to verify thin areas before slicing.' }
        ]
      },
      { slug: 'helmet', title: 'Text to 3D Helmet — AI Generator', h1: 'Turn Text Into a 3D Helmet', desc: 'Create custom helmet 3D models from text. Medieval, sci-fi, cosplay — AI generation optimized for 3D printing.', prompt: 'Spartan warrior helmet with bronze patina, red horsehair crest, battle-worn scratches', category: 'Characters', keywords: 'text to 3D helmet, AI helmet model, cosplay helmet 3D',
        tips: [
          'Name the helmet era or culture (Spartan, Viking, Samurai, futuristic) for authentic shape and ornamentation',
          'Describe the visor style — open face, T-slit, full face shield, retractable — to define the look',
          'Add surface finish details like "hammered bronze", "polished chrome", or "matte ceramic" for texture',
          'Mention accessories like crests, horns, plumes, antennas, or HUD visors for distinctive features'
        ],
        useCases: [
          { title: 'Cosplay Helmets', desc: 'Design and 3D print full-size wearable helmets for cosplay, conventions, and costume competitions.' },
          { title: 'Game Armor Sets', desc: 'Generate helmet models for RPG equipment systems, character customisation screens, and loot drops.' },
          { title: 'Collectible Display', desc: 'Create detailed helmet replicas of historical, fantasy, or sci-fi designs for shelf display and collector showcases.' }
        ],
        relatedPrompts: [
          'Mandalorian-style bounty hunter helmet with T-visor, weathered beskar steel, rangefinder antenna',
          'Viking spectacle helmet with chainmail aventail, iron nasal guard, aged patina',
          'Futuristic pilot helmet with transparent HUD visor, oxygen tubes, sleek white shell',
          'Samurai kabuto with golden crescent crest, menpo face guard, silk cord lacing',
          'Ancient Greek Corinthian helmet with cheek guards, horsehair crest, museum display stand'
        ],
        faq: [
          { q: 'Can I print a wearable helmet from the generated model?', a: 'Yes. Scale the model to your head measurements in your slicer, split into printable sections, and assemble with adhesive. Add padding and a chin strap after printing for a comfortable, wearable fit.' },
          { q: 'How do I ensure the helmet fits my head?', a: 'Measure your head circumference, then scale the model in your slicer to match. For precision, import into Blender and use a reference head model to check fit before printing.' },
          { q: 'Can the AI generate helmets with transparent visors?', a: 'The AI generates the visor geometry as a solid surface. After printing, replace the visor section with a thermoformed clear plastic sheet, or leave the visor area open and attach a separate transparent insert.' }
        ]
      },
      { slug: 'castle', title: 'Text to 3D Castle — AI Generator', h1: 'Turn Text Into a 3D Castle', desc: 'Describe a castle and get a detailed 3D model. Medieval fortresses, fantasy citadels, ruins — AI text-to-3D with GLB export.', prompt: 'Dark fantasy castle on cliff edge, gothic towers, stormy sky, ravens circling', category: 'Architecture', keywords: 'text to 3D castle, AI castle model, generate castle 3D',
        tips: [
          'Specify the castle type — motte-and-bailey, concentric fortress, mountaintop citadel — for distinct layouts',
          'Describe the condition: "pristine with banners flying", "crumbling ruins", "under siege" for narrative depth',
          'Include defensive features like drawbridges, moats, arrow slits, and battlements for realism',
          'Add atmosphere cues (stormy sky, moonlit, golden hour, fog) to influence the overall mood'
        ],
        useCases: [
          { title: 'Fantasy Game Levels', desc: 'Generate unique castle models for RPG dungeons, strategy game maps, and open-world fantasy environments.' },
          { title: 'Tabletop Terrain Centrepieces', desc: 'Print castle sections — keeps, walls, gate houses — as modular terrain for wargaming and D&D campaigns.' },
          { title: 'Story Illustration', desc: 'Create 3D castle renders for children\'s book illustrations, novel covers, and animated story backgrounds.' }
        ],
        relatedPrompts: [
          'Floating sky castle held aloft by chains and magic crystals, cloud layer below, high fantasy',
          'Japanese feudal castle (tenshu) with curved roofs, stone walls, cherry blossom courtyard',
          'Ruined desert fortress half-buried in sand dunes, sandstorm approaching, ancient civilisation',
          'Underwater coral castle with bioluminescent towers, merfolk kingdom, deep ocean',
          'Vampire\'s gothic castle with stained glass windows, gargoyles, and a thunderstorm backdrop'
        ],
        faq: [
          { q: 'Can I generate a castle with interior rooms?', a: 'The AI generates the exterior and visible structural features. For interior halls, dungeons, and throne rooms, generate each as a separate model and assemble them in Blender or your game engine.' },
          { q: 'How do I print a large castle model?', a: 'Split the model into sections (towers, walls, keep) in Blender, print each part separately, and glue them together. This also lets you paint each section individually before assembly.' },
          { q: 'Can I create modular castle pieces that connect?', a: 'Generate individual elements — a wall section, a tower, a gate — with consistent style keywords. Design connection points (pegs and slots) in Blender after export for a modular terrain system.' }
        ]
      },
    ]
  }
};

/**
 * Flat lookup: returns page data for a given path like /3d-models/dragon
 */
export function findSeoPage(pathname) {
  for (const [groupKey, group] of Object.entries(SEO_PAGES)) {
    for (const page of group.pages) {
      if (pathname === `${group.base}/${page.slug}`) {
        return { ...page, group: groupKey, basePath: group.base };
      }
    }
  }
  return null;
}

/**
 * Generate sitemap XML entries for all SEO pages
 */
export function generateSeoSitemap() {
  const entries = [];
  for (const [, group] of Object.entries(SEO_PAGES)) {
    for (const page of group.pages) {
      entries.push(`  <url>
    <loc>https://timrx.live${group.base}/${page.slug}</loc>
    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>`);
    }
  }
  return entries.join('\n');
}
